#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

set -xe

INPUT=$(jq -r .bold config.json)
MASK=$(jq -r .mask config.json)
if [ $MASK == "null" ]; then
    MASK=""
fi

APPROACH=$(jq -r .approach config.json)
KERNEL=$(jq -r .kernel config.json)
COMPONENTS=$(jq -r .n_components config.json)
RANDOM_STATE=$(jq -r .random_state config.json)

OPTS=""
if [ ! -z "$MASK" ]; then
    OPTS="$OPTS -mask $MASK"
fi

mkdir -p gradients

time singularity run -e \
    docker://anibalsolon/app-connectivity-gradient:v0.0.1 \
        $APPROACH $KERNEL $INPUT --n_components $COMPONENTS --random_state $RANDOM_STATE $OPTS
